"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SystemErrorBar = SystemErrorBar;
const jsx_runtime_1 = require("react/jsx-runtime");
const utils_1 = require("../../lib/utils");
/**
 * SystemErrorBar - Displays system-level errors at the top of the dashboard.
 * Used for unexpected failures, invariant violations, and uncaught exceptions.
 * Shows a generic message with retry and log reference options.
 */
function SystemErrorBar({ message = 'Something went wrong. The application encountered an unexpected error.', correlationId, onRetry, onViewLogs, onDismiss, className, testId = 'system-error-bar' }) {
    return ((0, jsx_runtime_1.jsxs)("div", { className: (0, utils_1.cn)('flex items-center gap-3 border-b border-red-500/40 bg-red-500/20 px-4 py-2 text-[11px]', className), role: "alert", "aria-live": "polite", "data-testid": testId, children: [(0, jsx_runtime_1.jsx)("svg", { className: "h-5 w-5 flex-shrink-0 text-red-400", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 2, "aria-hidden": "true", children: (0, jsx_runtime_1.jsx)("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" }) }), (0, jsx_runtime_1.jsxs)("div", { className: "flex-1 min-w-0", children: [(0, jsx_runtime_1.jsx)("p", { className: "font-medium text-red-200", children: message }), correlationId && ((0, jsx_runtime_1.jsxs)("p", { className: "mt-0.5 text-[9px] text-red-300/70 font-mono", children: ["Error ID: ", correlationId] }))] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-2 flex-shrink-0", children: [onRetry && ((0, jsx_runtime_1.jsxs)("button", { type: "button", onClick: onRetry, className: "flex items-center gap-1 rounded border border-red-400/30 bg-red-500/20 px-2 py-1 text-[10px] font-medium text-red-200 hover:bg-red-500/30 transition-colors", "data-testid": `${testId}-retry`, children: [(0, jsx_runtime_1.jsx)("svg", { className: "h-3 w-3", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 2, children: (0, jsx_runtime_1.jsx)("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" }) }), "Retry"] })), onViewLogs && ((0, jsx_runtime_1.jsxs)("button", { type: "button", onClick: onViewLogs, className: "flex items-center gap-1 rounded border border-red-400/30 px-2 py-1 text-[10px] font-medium text-red-300/80 hover:text-red-200 hover:bg-red-500/10 transition-colors", "data-testid": `${testId}-view-logs`, children: [(0, jsx_runtime_1.jsx)("svg", { className: "h-3 w-3", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 2, children: (0, jsx_runtime_1.jsx)("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" }) }), "View Logs"] })), onDismiss && ((0, jsx_runtime_1.jsx)("button", { type: "button", onClick: onDismiss, className: "text-red-300/70 hover:text-red-200", "aria-label": "Dismiss error", "data-testid": `${testId}-dismiss`, children: (0, jsx_runtime_1.jsx)("svg", { className: "h-4 w-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 2, children: (0, jsx_runtime_1.jsx)("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M6 18L18 6M6 6l12 12" }) }) }))] })] }));
}
exports.default = SystemErrorBar;
