"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ODDS_API_IO_BOOKMAKER_REGION_BY_NAME = void 0;
exports.ODDS_API_IO_BOOKMAKER_REGION_BY_NAME = {
    '10BET': 'International',
    '12bet': 'International',
    '188bet': 'International',
    '18bet': 'International',
    '1Bet': 'International',
    '1xbet': 'International',
    '20Bet': 'International',
    '31Bet': 'International',
    '7Bet LT': 'Lithuania',
    '888Sport': 'International',
    '888Sport CA': 'Canada',
    '888Sport IT': 'Italy',
    'ATG SE': 'Sweden',
    'AdmiralBet DE': 'Germany',
    'AdmiralBet IT': 'Italy',
    'All British Casino': 'United Kingdom',
    AlphaWin: 'Cyprus',
    Apostamax: 'Brazil',
    Apostatudo: 'Brazil',
    'Apuesta Total': 'Peru',
    B2xbet: 'International',
    'BC.Game': 'International',
    BRX: 'Brazil',
    'Bally Bet': 'United States',
    BandBet: 'Brazil',
    'BarriereBet FR': 'France',
    'Bet Da Sorte': 'Brazil',
    'Bet-At-Home': 'International',
    'Bet.bet': 'International',
    Bet365: 'International',
    Bet7k: 'Brazil',
    'BetFlag IT': 'Italy',
    BetMGM: 'United States',
    'BetMGM BR': 'Brazil',
    BetOnRed: 'International',
    'BetOnline.ag': 'International',
    BetParx: 'United States',
    BetRivers: 'United States',
    BetUK: 'United Kingdom',
    BetVictor: 'International',
    BetWinner: 'International',
    Betano: 'International',
    'Betano BG': 'Bulgaria',
    'Betano BR': 'Brazil',
    'Betano CA': 'Canada',
    'Betano DE': 'Germany',
    'Betano DK': 'Denmark',
    'Betano MX': 'Mexico',
    'Betano PE': 'Peru',
    'Betano PT': 'Portugal',
    'Betano UK': 'United Kingdom',
    'Betcenter BE': 'Belgium',
    'Betclic FR': 'France',
    'Betclic PL': 'Poland',
    Betcris: 'International',
    'Betfair ES': 'Spain',
    'Betfair Exchange': 'International',
    'Betfair IT': 'Italy',
    'Betfair Sportsbook': 'International',
    Betfalcons: 'International',
    'Betfan PL': 'Poland',
    Betfinal: 'International',
    Betfury: 'International',
    Betfusion: 'International',
    Betgorillas: 'International',
    Betify: 'International',
    'Betinia DK': 'Denmark',
    Betnacional: 'Brazil',
    Betplay: 'Colombia',
    Betsafe: 'International',
    Betsson: 'International',
    Betway: 'International',
    Blaze: 'Brazil',
    Bluechip: 'International',
    'BookMaker.eu': 'International',
    Bovada: 'International',
    BoyleSports: 'Ireland',
    BullSbet: 'Brazil',
    Bwin: 'International',
    'Bwin ES': 'Spain',
    'Bwin FR': 'France',
    'Bwin IT': 'Italy',
    CASHPOINT: 'Austria',
    Caesars: 'United States',
    CampeonBet: 'Spain',
    'Campobet DK': 'Denmark',
    'Casa Pariurilor': 'Romania',
    Cassino: 'Brazil',
    'Chance.cz': 'Czech Republic',
    Circa: 'United States',
    'CircusBet FR': 'France',
    CloudBet: 'International',
    Coolbet: 'International',
    Coolzino: 'International',
    Coral: 'United Kingdom',
    CrazyBuzzer: 'International',
    CryptoLeo: 'International',
    DACHBET: 'Germany',
    DafaBet: 'International',
    DanskeSpil: 'Denmark',
    Donaldbet: 'Brazil',
    DraftKings: 'United States',
    'Dream.bet': 'International',
    Duel: 'United States',
    'ESPN BET': 'United States',
    Epicbet: 'Romania',
    'Esportiva Bet': 'Brazil',
    'Estrela Bet': 'Brazil',
    'Eurobet IT': 'Italy',
    'Expekt DK': 'Denmark',
    'Expekt SE': 'Sweden',
    'FB Sports': 'International',
    FDJ: 'France',
    'FG6 (Loterj)': 'Turkey',
    'Fair999 Exchange': 'International',
    FairPari: 'International',
    FanDuel: 'United States',
    Fanatics: 'United States',
    Fezbet: 'International',
    Fliff: 'United States',
    FortuneJack: 'International',
    FreshBet: 'International',
    Gamdom: 'International',
    Gana777: 'India',
    'Goldbet IT': 'Italy',
    'Golden Palace Sports BE': 'Belgium',
    GoldenBet: 'International',
    GreatWin: 'International',
    HKJC: 'Hong Kong',
    Hanzbet: 'International',
    'Hard Rock Bet': 'United States',
    Iddaa: 'Turkey',
    Inbet: 'Bulgaria',
    Inkabet: 'Peru',
    Interwetten: 'International',
    Ivibet: 'International',
    JackBit: 'International',
    Jogão: 'Brazil',
    JustBet: 'International',
    KTO: 'Brazil',
    Kalshi: 'United States',
    Kambi: 'International',
    'LVbet PL': 'Poland',
    Ladbrokes: 'United Kingdom',
    'Ladbrokes DE': 'Germany',
    LeoVegas: 'International',
    'LeoVegas DK': 'Denmark',
    'LeoVegas ES': 'Spain',
    'LeoVegas IT': 'Italy',
    'LeoVegas NL': 'Netherlands',
    'LeoVegas Sport': 'International',
    LibraBet: 'International',
    Liderbet: 'International',
    LiveScoreBet: 'United Kingdom',
    Lottoland: 'International',
    'Lottomatica IT': 'Italy',
    'LowVig AG': 'International',
    'Luckia ES': 'Spain',
    M88: 'International',
    Marathonbet: 'International',
    MegaPari: 'International',
    MelBet: 'International',
    'Merkur Bets': 'Germany',
    'MerkurXtip CZ': 'Czech Republic',
    Mmabet: 'International',
    'Mozzart Bet': 'Serbia',
    'Mr. Jack': 'Italy',
    MrGreen: 'International',
    MyBookie: 'International',
    Mystake: 'International',
    NetBet: 'International',
    Nextbet: 'International',
    Ninecasino: 'International',
    NordicBet: 'International',
    'NordicBet DK': 'Denmark',
    'Norsk Tipping': 'Norway',
    Novibet: 'International',
    'Orbit Exchange': 'International',
    'PAF ES': 'Spain',
    PAGBET: 'Brazil',
    PMU: 'France',
    'Paddy Power': 'Ireland',
    Pamestoixima: 'Greece',
    'Parimatch UK': 'United Kingdom',
    'Piwi247 Exchange': 'International',
    'Pix Bet': 'Brazil',
    Pixbet: 'Brazil',
    'Planetwin365 IT': 'Italy',
    'PointsBet AU': 'Australia',
    'PokerStars FR': 'France',
    'PokerStars IT': 'Italy',
    Polymarket: 'International',
    Powbet: 'International',
    PrizePicks: 'United States',
    'Prophet Exchange': 'Australia',
    Qbet: 'International',
    QuickWin: 'International',
    'Quigioco IT': 'Italy',
    Rabona: 'International',
    Rainbet: 'International',
    RajBet: 'International',
    Ricobet: 'International',
    Rollbit: 'International',
    Rolletto: 'International',
    Roobet: 'International',
    'STS PL': 'Poland',
    Sbobet: 'International',
    Sbobet_2: 'International',
    'Sharp Exchange': 'International',
    SingBet: 'International',
    'Sisal IT': 'Italy',
    Skybet: 'United Kingdom',
    'Snai IT': 'Italy',
    Sortenabet: 'Denmark',
    'Spelet LV': 'Latvia',
    'SportBetting AG': 'International',
    Sportaza: 'International',
    SportingBet: 'International',
    'SportingBet ZA': 'South Africa',
    'Sportingbet BR': 'Brazil',
    Sports411: 'International',
    'Sportsbet.com.au': 'Australia',
    SportyBet: 'International',
    Stake: 'International',
    'Stake.bet.br': 'Brazil',
    'Stanleybet IT': 'Italy',
    Stoiximan: 'Greece',
    SugarHouse: 'United States',
    Superbet: 'International',
    SvenskaSpel: 'Sweden',
    'TABtouch AU': 'Australia',
    'Tab AU': 'Australia',
    'Tiger Gaming': 'International',
    'Tipico DE': 'Germany',
    Tippmix: 'Hungary',
    TippmixPRO: 'Hungary',
    'Tipsport.cz': 'Czech Republic',
    TonyBet: 'International',
    Underdog: 'United States',
    Unibet: 'International',
    'Unibet AU': 'Australia',
    'Unibet BE': 'Belgium',
    'Unibet DK': 'Denmark',
    'Unibet FR': 'France',
    'Unibet IT': 'Italy',
    'Unibet SE': 'Sweden',
    'Unibet UK': 'United Kingdom',
    Vave: 'International',
    Vbet: 'International',
    'Vbet BR': 'Brazil',
    Veikkaus: 'Finland',
    VeloBet: 'International',
    Verabet: 'International',
    WELTBET: 'Germany',
    Wazamba: 'International',
    WilliamHill: 'United Kingdom',
    'WilliamHill NJ': 'United States',
    'Winamax DE': 'Germany',
    'Winamax FR': 'France',
    'Winpot MX': 'Mexico',
    'ZEbet FR': 'France',
    'bet365 NJ': 'United States',
    'eFortuna PL': 'Poland',
    paf: 'International'
};
